export const usersData = [
  {
    id: 1,
    full_name: "Aarav Mehta",
    username: "aaravm",
    age: 24,
    gender: "Male",
    email: "aarav@example.com",
    total_posts: 120,
    total_likes: 5423,
    total_shares: 231,
    status: "active",
    registration_date: "2023-06-15T10:23:00Z",
  },
  {
    id: 2,
    full_name: "Simran Kaur",
    username: "simrank",
    age: 21,
    gender: "Female",
    email: "simran@example.com",
    total_posts: 89,
    total_likes: 3212,
    total_shares: 118,
    status: "pending",
    registration_date: "2023-11-02T08:12:00Z",
  },
  {
    id: 3,
    full_name: "Rohan Verma",
    username: "rohanv",
    age: 26,
    gender: "Male",
    email: "rohan@example.com",
    total_posts: 300,
    total_likes: 10233,
    total_shares: 654,
    status: "block",
    registration_date: "2022-01-10T13:30:00Z",
  },
  {
    id: 4,
    full_name: "Neha Sharma",
    username: "neha_sh",
    age: 23,
    gender: "Female",
    email: "neha@example.com",
    total_posts: 150,
    total_likes: 7301,
    total_shares: 300,
    status: "active",
    registration_date: "2024-03-05T16:40:00Z",
  },
];

export const postsData = [
  {
    id: 1,
    user: {
      full_name: "Aarav Mehta",
      username: "aaravm",
    },
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkdPFA6r_IbzQJcyXrKT5TSritv0S_iWwFmw&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQv5R_TCbEHyx_z3r72Dh5TGXMWp33gz5uE-A&s",
    ],
    video: "https://www.example.com/video1.mp4",
    description: "Exploring the hills! 🌄 #travel #nature",
    tags: ["travel", "nature"],
    likes: 1203,
    comments: 75,
    shares: 30,
    status: "active",
    created_at: "2024-07-01T12:00:00Z",
  },
  {
    id: 2,
    user: {
      full_name: "Neha Sharma",
      username: "neha_sh",
    },
    images: [],
    video: "",
    description: "Just a quiet day with coffee ☕️",
    tags: ["coffee", "lifestyle"],
    likes: 642,
    comments: 12,
    shares: 4,
    status: "reported",
    created_at: "2024-06-28T09:30:00Z",
  },
  {
    id: 3,
    user: {
      full_name: "Rohan Verma",
      username: "rohanv",
    },
    images: [
      "food1.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkdPFA6r_IbzQJcyXrKT5TSritv0S_iWwFmw&s",
      "food3.jpg",
    ],
    video: "",
    description: "Made some homemade pasta today! 🍝",
    tags: ["food", "homemade"],
    likes: 982,
    comments: 41,
    shares: 15,
    status: "block",
    created_at: "2024-06-25T18:45:00Z",
  },
];

